= Lossy Image Processor

Image encoder and decoder that uses many different techniques to achieve good balance between entropy and quality of an image.

== Usage


Type `lip --help` to get help. General usage:
----
lip (--encode|--decode) [-s] source dest
----
=== Available options
----
  -e,--encode                 Encode a file
  -d,--decode                 Decode a file
  -h,--help                   Print help message and exit
  -s,--stats                  Print stats during and after encoding process.
----

=== Examples

*Encoding file*
----
./lip --encode -s image.tga output.lip
----
*Decoding file*
----
./lip -d -s output.lip image2.tga
----


== Project structure

There are currently 3 projects in this workspace.

=== External libraries

_LIP_Core_ library doesn't have any external dependencies except C++ standard library.

* https://github.com/CLIUtils/CLI11[CLI11] provides command-line arguments parser for _LZW_CLI_.
* https://github.com/catchorg/Catch2[Catch2] is used in _LZW_Core_Tests_ as a testing framework.

== Building

You need https://premake.github.io/download.html[Premake5] to easily generate project files (e.g. for Visual Studio, Code::Blocks, Xcode, GNU Make and more)

In root folder run `premake5` with an argument depending on IDE you want to use. For example, run: `premake5 vs2019` if you want to generate project for Visual Studio 2019.


=== Visual Studio (Windows)
In root folder run `premak5 vs2019`. Visual Studio solution with projects will be generated. Open `LZW.sln` with Visual Studio. Everything should be configured properly to build, run and test the program.

=== Makefile (Linux)
In root folder run `premake5 [--cc=gcc|clang] gmake2`. If `--cc` option is not set, then default C++ compiler will be used. Makefile files structure will be generated. In root folder run `make help` to get available build options. General usage is:
----
make [config=release|debug] [target]

TARGETS:
    all (default)
    LIP_CLI
    LIP_Core
    LIP_Core_Tests
----


== Tests

Project _LIP_Core_Tests_ contains all the tests for _LIP_Core_. You can build it and run executable `lip_core_tests` to verify the tests.

== License

Copyright © 2020 Sebastian Fojcik +
Use of this software is granted under the terms of the MIT License.

See the link:LICENCE[LICENSE] for the full license text.
